/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EsSearch: typeof import('./../components/common/EsSearch/index.vue')['default']
    EsTable: typeof import('./../components/common/EsTable/index.vue')['default']
    FaAuth: typeof import('./../ui/components/FaAuth/index.vue')['default']
    FaAvatar: typeof import('./../ui/components/FaAvatar/index.vue')['default']
    FaButton: typeof import('./../ui/components/FaButton/index.vue')['default']
    FaCard: typeof import('./../ui/components/FaCard/index.vue')['default']
    FaCheckbox: typeof import('./../ui/components/FaCheckbox/index.vue')['default']
    FaContextMenu: typeof import('./../ui/components/FaContextMenu/index.vue')['default']
    FaDivider: typeof import('./../ui/components/FaDivider/index.vue')['default']
    FaDrawer: typeof import('./../ui/components/FaDrawer/index.vue')['default']
    FaDropdown: typeof import('./../ui/components/FaDropdown/index.vue')['default']
    FaFixedActionBar: typeof import('./../ui/components/FaFixedActionBar/index.vue')['default']
    FaIcon: typeof import('./../ui/components/FaIcon/index.vue')['default']
    FaInput: typeof import('./../ui/components/FaInput/index.vue')['default']
    FaKbd: typeof import('./../ui/components/FaKbd/index.vue')['default']
    FaModal: typeof import('./../ui/components/FaModal/index.vue')['default']
    FaNotAllowed: typeof import('./../ui/components/FaNotAllowed/index.vue')['default']
    FaNotification: typeof import('./../ui/components/FaNotification/index.vue')['default']
    FaPageHeader: typeof import('./../ui/components/FaPageHeader/index.vue')['default']
    FaPageMain: typeof import('./../ui/components/FaPageMain/index.vue')['default']
    FaPasswordStrength: typeof import('./../ui/components/FaPasswordStrength/index.vue')['default']
    FaPinInput: typeof import('./../ui/components/FaPinInput/index.vue')['default']
    FaPopover: typeof import('./../ui/components/FaPopover/index.vue')['default']
    FaScrollArea: typeof import('./../ui/components/FaScrollArea/index.vue')['default']
    FaSearchBar: typeof import('./../ui/components/FaSearchBar/index.vue')['default']
    FaSelect: typeof import('./../ui/components/FaSelect/index.vue')['default']
    FaSmartFixedBlock: typeof import('./../ui/components/FaSmartFixedBlock/index.vue')['default']
    FaSwitch: typeof import('./../ui/components/FaSwitch/index.vue')['default']
    FaSystemInfo: typeof import('./../ui/components/FaSystemInfo/index.vue')['default']
    FaTabs: typeof import('./../ui/components/FaTabs/index.vue')['default']
    FaToast: typeof import('./../ui/components/FaToast/index.vue')['default']
    FaTooltip: typeof import('./../ui/components/FaTooltip/index.vue')['default']
    FileUpload: typeof import('./../components/upload/FileUpload/index.vue')['default']
    ImagePreview: typeof import('./../components/display/ImagePreview/index.vue')['default']
    ImagesUpload: typeof import('./../components/upload/ImagesUpload/index.vue')['default']
    ImageUpload: typeof import('./../components/upload/ImageUpload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const EsSearch: typeof import('./../components/common/EsSearch/index.vue')['default']
  const EsTable: typeof import('./../components/common/EsTable/index.vue')['default']
  const FaAuth: typeof import('./../ui/components/FaAuth/index.vue')['default']
  const FaAvatar: typeof import('./../ui/components/FaAvatar/index.vue')['default']
  const FaButton: typeof import('./../ui/components/FaButton/index.vue')['default']
  const FaCard: typeof import('./../ui/components/FaCard/index.vue')['default']
  const FaCheckbox: typeof import('./../ui/components/FaCheckbox/index.vue')['default']
  const FaContextMenu: typeof import('./../ui/components/FaContextMenu/index.vue')['default']
  const FaDivider: typeof import('./../ui/components/FaDivider/index.vue')['default']
  const FaDrawer: typeof import('./../ui/components/FaDrawer/index.vue')['default']
  const FaDropdown: typeof import('./../ui/components/FaDropdown/index.vue')['default']
  const FaFixedActionBar: typeof import('./../ui/components/FaFixedActionBar/index.vue')['default']
  const FaIcon: typeof import('./../ui/components/FaIcon/index.vue')['default']
  const FaInput: typeof import('./../ui/components/FaInput/index.vue')['default']
  const FaKbd: typeof import('./../ui/components/FaKbd/index.vue')['default']
  const FaModal: typeof import('./../ui/components/FaModal/index.vue')['default']
  const FaNotAllowed: typeof import('./../ui/components/FaNotAllowed/index.vue')['default']
  const FaNotification: typeof import('./../ui/components/FaNotification/index.vue')['default']
  const FaPageHeader: typeof import('./../ui/components/FaPageHeader/index.vue')['default']
  const FaPageMain: typeof import('./../ui/components/FaPageMain/index.vue')['default']
  const FaPasswordStrength: typeof import('./../ui/components/FaPasswordStrength/index.vue')['default']
  const FaPinInput: typeof import('./../ui/components/FaPinInput/index.vue')['default']
  const FaPopover: typeof import('./../ui/components/FaPopover/index.vue')['default']
  const FaScrollArea: typeof import('./../ui/components/FaScrollArea/index.vue')['default']
  const FaSearchBar: typeof import('./../ui/components/FaSearchBar/index.vue')['default']
  const FaSelect: typeof import('./../ui/components/FaSelect/index.vue')['default']
  const FaSmartFixedBlock: typeof import('./../ui/components/FaSmartFixedBlock/index.vue')['default']
  const FaSwitch: typeof import('./../ui/components/FaSwitch/index.vue')['default']
  const FaSystemInfo: typeof import('./../ui/components/FaSystemInfo/index.vue')['default']
  const FaTabs: typeof import('./../ui/components/FaTabs/index.vue')['default']
  const FaToast: typeof import('./../ui/components/FaToast/index.vue')['default']
  const FaTooltip: typeof import('./../ui/components/FaTooltip/index.vue')['default']
  const FileUpload: typeof import('./../components/upload/FileUpload/index.vue')['default']
  const ImagePreview: typeof import('./../components/display/ImagePreview/index.vue')['default']
  const ImagesUpload: typeof import('./../components/upload/ImagesUpload/index.vue')['default']
  const ImageUpload: typeof import('./../components/upload/ImageUpload/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}